CREATE TABLE ACCOUNT (
    ACNO NUMBER PRIMARY KEY,
    CNAME VARCHAR2(50),
    BNAME VARCHAR2(50),
    BALANCE NUMBER(12,2)
);

CREATE OR REPLACE FUNCTION GET_BALANCE (p_acno IN NUMBER) 
RETURN NUMBER IS
    v_balance ACCOUNT.BALANCE%TYPE;
BEGIN
    SELECT BALANCE INTO v_balance 
    FROM ACCOUNT 
    WHERE ACNO = p_acno;
    
    RETURN v_balance;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN NULL; -- Returns null if account is missing
END;
/
