CREATE OR REPLACE TRIGGER TR_SET_EMP_TITLE
BEFORE INSERT OR UPDATE ON EMP
FOR EACH ROW
BEGIN
    IF :NEW.GENDER = 'MALE' AND UPPER(:NEW.ENAME) NOT LIKE 'MR.%' THEN
        :NEW.ENAME := 'MR. ' || :NEW.ENAME;
    ELSIF :NEW.GENDER = 'FEMALE' AND UPPER(:NEW.ENAME) NOT LIKE 'MS.%' THEN
        :NEW.ENAME := 'MS. ' || :NEW.ENAME;
    END IF;
END;
/
